import datetime
from typing import Any, Optional, TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base

if TYPE_CHECKING:
    from app.models.conversation import Conversation


class MessageRole:
    """Role constants for conversation messages."""

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class Message(Base):
    """
    A single turn (user or assistant) within a Conversation.

    Token tracking
    --------------
    prompt_tokens     — tokens in the input prompt sent to the LLM
    completion_tokens — tokens generated by the LLM in this message
    total_tokens      — prompt + completion (stored for fast aggregation)

    citations
    ---------
    Stored as JSONB so the full source metadata (score, chunk_uuid,
    parsed_document_id) is preserved without additional joins.
    Schema: [{"score": float, "chunk_uuid": str, "parsed_document_id": int}]
    """

    __tablename__ = "messages"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    conversation_id: Mapped[int] = mapped_column(
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # "user" | "assistant" | "system"
    role: Mapped[str] = mapped_column(String(20), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)

    # JSONB for zero-schema-change extensibility.
    citations: Mapped[Optional[Any]] = mapped_column(JSONB, nullable=True)

    # Token accounting — stored per-message, not computed at query time.
    prompt_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    completion_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    total_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ── Relationships ────────────────────────────────────────────────────────
    conversation: Mapped["Conversation"] = relationship(back_populates="messages")
