"""Add new fields description

Revision ID: 07b24f13ad0a
Revises: 5d5e7c4a95d4
Create Date: 2026-06-30 18:28:51.501406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b24f13ad0a'
down_revision: Union[str, Sequence[str], None] = '5d5e7c4a95d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
