"""create_parsed_document_model

Revision ID: b78266f6e37a
Revises: cfd6c36167d5
Create Date: 2026-07-01 14:51:32.680792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78266f6e37a'
down_revision: Union[str, Sequence[str], None] = 'cfd6c36167d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('language_confidence', sa.Float(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_documents_document_id'), 'parsed_documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_parsed_documents_id'), 'parsed_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_documents_id'), table_name='parsed_documents')
    op.drop_index(op.f('ix_parsed_documents_document_id'), table_name='parsed_documents')
    op.drop_table('parsed_documents')
    # ### end Alembic commands ###
