"""add_sha256_hash_and_make_language_nullable

Revision ID: cfd6c36167d5
Revises: f57e946a519e
Create Date: 2026-07-01 01:27:16.084849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd6c36167d5'
down_revision: Union[str, Sequence[str], None] = 'f57e946a519e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('sha256_hash', sa.String(length=64), nullable=True))
    op.alter_column('documents', 'language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('documents', 'sha256_hash')
    # ### end Alembic commands ###
