"""add_audit_fields_to_kb_and_doc

Revision ID: f57e946a519e
Revises: 713933a654f8
Create Date: 2026-07-01 00:50:51.227967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57e946a519e'
down_revision: Union[str, Sequence[str], None] = '713933a654f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('knowledge_bases', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'knowledge_bases', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'knowledge_bases', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.drop_column('knowledge_bases', 'updated_by')
    op.drop_column('knowledge_bases', 'created_by')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'updated_by')
    op.drop_column('documents', 'created_by')
    # ### end Alembic commands ###
